#!/bin/bash
# https://blog.fhrnet.eu/2017/10/29/postfix-routing-outgoing-email-to-relay-based-on-sender-domain/

echo "##### CONFIGURING POSTFIX #####"

relays="#Generated by start.sh\n"
counter=1

while [ -n "$(eval echo \$EMAIL_${counter})" ]; do
  echo "Relaying from $(eval echo \$EMAIL_${counter}) via $(eval echo \$SERVER_${counter})"
  relays+="$(eval echo \$EMAIL_${counter})    $(eval echo \$SERVER_${counter})\n"
  ((counter++))
done

credentials="#Generated by start.sh\n"
counter=1

while [ -n "$(eval echo \$EMAIL_${counter})" ]; do
  credentials+="$(eval echo \$SERVER_${counter})    $(eval echo \$CREDENTIALS_${counter})\n"
  ((counter++))
done


printf "$relays" > /etc/postfix/relay_maps
postmap /etc/postfix/relay_maps

printf "$credentials" > /etc/postfix/sasl_passwd
postmap /etc/postfix/sasl_passwd

echo "setting allowed networks"
postconf -e "mynetworks $TRUSTED_NETWORKS"

echo "configuration done"
echo "##### STARTING POSTFIX #####"


exec postfix start-fg

echo 