kind: pipeline
type: docker
name: default

steps:
- name: test
  image: docker
  privileged: true
  commands:
  - apk update
  - apk add git
  - echo "Before\:$DRONE_COMMIT_BEFORE"
  - echo "After\:$DRONE_COMMIT_AFTER"
  - echo "Commit\:$DRONE_COMMIT"
  - |
    for dir in $(ls -d */); do
      if ! git diff --quiet $DRONE_COMMIT_BEFORE -- $dir; then
        echo "Changes in $dir"
      fi
        docker build -t "https://ghcr.io/rahn-it/$dir" $dir
    done
  