kind: pipeline
type: docker
name: default

volumes:
- name: docker-sock
  host:
    path: /var/run/docker.sock

steps:
- name: test
  image: docker
  privileged: true
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock
  commands:
  - apk update
  - apk add git
  - echo "Before\:$DRONE_COMMIT_BEFORE"
  - echo "After\:$DRONE_COMMIT_AFTER"
  - echo "Commit\:$DRONE_COMMIT"
  - |
    for dir in $(ls -d */); do
      echo "found dir $dir"
      image=$${dir::-1}
      echo "Building $image ..."
      if ! git diff --quiet $DRONE_COMMIT_BEFORE -- $dir; then
        echo "Changes in $image"
      fi
        docker build -t "rahn-it/$image" $dir
    done
  