kind: pipeline
type: docker
name: default

steps:
- name: test
  image: docker
  privileged: true
  commands:
  - apk update
  - apk add git
  - echo "Before\:$DRONE_COMMIT_BEFORE"
  - echo "After\:$DRONE_COMMIT_AFTER"
  - echo "Commit\:$DRONE_COMMIT"
  - git diff $DRONE_COMMIT_BEFORE
  