kind: pipeline
type: docker
name: default

volumes:
- name: docker-sock
  host:
    path: /var/run/docker.sock

steps:
- name: test
  image: docker
  privileged: true
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock
  environment:
    GITHUB_USER:
      from_secret: GITHUB_USER
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  commands:
  - apk update
  - apk add git
  - docker login ghcr.io -u "$GITHUB_USER" -p "$GITHUB_TOKEN" 
  - echo "Trigger DRONE_BUILD_TRIGGER"
  - |
    for dir in $(ls -d */); do
      echo "found dir $dir"
      image=$${dir::-1}
      if (! git diff --quiet $DRONE_COMMIT_BEFORE -- $dir) || $BUILD_ALL; then
        echo "Building $image ..."
        docker build -t "ghcr.io/rahn-it/$image" --squash $dir
        docker push "ghcr.io/rahn-it/$image"
      fi
    done
  