name: Build to ghcr.io
on:
  push:
    branches:
      - master
  schedule:
  - cron: "2 0 * * SAT"
  workflow_dispatch:

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    container:
      image: docker
    steps:
      - name: Add Git
        run: apk update && apk add git
      - name: Clone
        run: git clone --depth 100 $(echo "${{ gitea.event.repository.clone_url }}" | sed -e "s^//^//:${{ gitea.token }}@^") .
      - run: |
          echo "triggered by ${{ gitea.event_name }}"
          docker login ghcr.io -u "${{ secrets.ghcr_user }}" -p "${{ secrets.ghcr_token }}"
          for dir in $(ls -d */); do
            echo "found dir $dir"
            image=${dir::-1}
            if (! git diff --quiet ${{ gitea.event.before }} ${{ gitea.event.after }} $dir) || [ "${{ gitea.event_name }}" = "schedule" ]; then
              echo "Building $image ..."
              docker build --pull -t "ghcr.io/rahn-it/$image" --squash $dir
              docker push "ghcr.io/rahn-it/$image"
            else
              echo "no changes in $dir"
            fi
          done