name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    container:
      image: docker
      # volumes:
      #   - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Add Git
        run: apk update && apk add git
      - name: Clone
        run: git clone --depth 1 $(echo "${{ gitea.event.repository.clone_url }}" | sed -e "s^//^//:${{ gitea.token }}@^") .
      - run: |
          docker login ghcr.io -u "${{ secrets.ghcr_user }}" -p "${{ secrets.ghcr_token }}"
          for dir in $(ls -d */); do
            echo "found dir $dir"
            image=${dir::-1}
            if (! git diff --quiet ${{ gitea.event.before }} -- $dir) || [ ! -z "$BUILD_ALL" ]; then
              echo "Building $image ..."
              docker build -t "ghcr.io/rahn-it/$image" --squash $dir
              docker push "ghcr.io/rahn-it/$image"
            fi
          done