#!/bin/bash

echo "##### CONFIGURING MOSQUITTO #####"

config="#Generated by start.sh\n"

config+="listener $PORT\n"
echo "port set to $PORT"

if [ -n "$USERNAME" -a -n "$PASSWORD" ]; then
    echo "username and password set"
    touch /mosquitto/config/mosquitto_passwd
    chmod 600 /mosquitto/config/mosquitto_passwd
    mosquitto_passwd -c -b /mosquitto/config/mosquitto_passwd "$USERNAME" "$PASSWORD"
    chown mosquitto:mosquitto /mosquitto/config/mosquitto_passwd
    config+="password_file /mosquitto/config/mosquitto_passwd\n"
else
    echo "username and password not set"
    rm -f /mosquitto/config/mosquitto_passwd
    config+="allow_anonymous true\n"
fi

printf "$config" > /mosquitto/config/mosquitto.conf
echo "configuration done"

echo "##### STARTING MOSQUITTO #####"

exec mosquitto -c /mosquitto/config/mosquitto.conf